name: Keep Alive Ping

on:
  schedule:
    # Runs every 14 minutes
    - cron: '*/14 * * * *'
  workflow_dispatch:

jobs:
  ping_service:
    runs-on: ubuntu-latest
    steps:
      - name: Send keep-alive request (Ignoring 404 Error)
        run: |
          # The --fail flag has been removed. 
          # The -sS flags suppress output but still ensure curl runs.
          curl -sS "https://password-manger-jwwi.onrender.com"